"""Added GaugeData retrieval timestamp

Revision ID: 2c53847a582a
Revises: 3a3d56493a83
Create Date: 2017-05-27 01:29:54.607417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c53847a582a'
down_revision = '3a3d56493a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GaugeData', sa.Column('retrieved', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GaugeData', 'retrieved')
    # ### end Alembic commands ###
