"""social


Revision ID: 352e12e0f114
Revises: 3f69a0a6351f
Create Date: 2017-05-22 16:08:02.658574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352e12e0f114'
down_revision = '3f69a0a6351f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
