"""update gauge

Revision ID: 3a3d56493a83
Revises: d985ac790876
Create Date: 2017-05-22 16:48:51.318993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a3d56493a83'
down_revision = 'd985ac790876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Gauges', sa.Column('usgs_id', sa.Integer(), nullable=True))
    op.drop_column('Gauges', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Gauges', sa.Column('url', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('Gauges', 'usgs_id')
    # ### end Alembic commands ###
