"""booger

Revision ID: 3f69a0a6351f
Revises: 736770ea815f
Create Date: 2017-05-20 09:30:22.226850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f69a0a6351f'
down_revision = '736770ea815f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
