"""get it working again

Revision ID: 4e75f34ff56a
Revises: 2c53847a582a
Create Date: 2017-05-29 22:34:25.457485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e75f34ff56a'
down_revision = '2c53847a582a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('UQ_GaugeData_gauge_id__timestamp', 'GaugeData', ['gauge_id', 'timestamp'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('UQ_GaugeData_gauge_id__timestamp', 'GaugeData', type_='unique')
    # ### end Alembic commands ###
