"""now with flask app import

Revision ID: 5e410e5c207d
Revises: 8d90d0ccff39
Create Date: 2017-05-20 08:59:34.044751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e410e5c207d'
down_revision = '8d90d0ccff39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
