"""now this is just getting ridiculous

Revision ID: 736770ea815f
Revises: 5e410e5c207d
Create Date: 2017-05-20 09:19:28.060655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736770ea815f'
down_revision = '5e410e5c207d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
