"""tryna get this shit to work

Revision ID: 7a58a24620c6
Revises: 97cd7f996752
Create Date: 2017-05-20 06:55:20.078806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a58a24620c6'
down_revision = '97cd7f996752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
