"""delete all the boogers

Revision ID: d2740d6e432b
Revises: 4e75f34ff56a
Create Date: 2017-06-03 16:12:08.066690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2740d6e432b'
down_revision = '4e75f34ff56a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Boogers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Boogers',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('Color', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('Person', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Person'], [u'Users.id'], name=u'boogers_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
