"""add UC for area

Revision ID: dfbc43ed1ba3
Revises: d2740d6e432b
Create Date: 2017-06-18 15:51:44.207450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfbc43ed1ba3'
down_revision = 'd2740d6e432b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_area_name_uc', 'Areas', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_area_name_uc', 'Areas', type_='unique')
    # ### end Alembic commands ###
